apiVersion: v1
kind: Pod
metadata:
  name: pod-config-map
spec:
  containers:
    - name: pod-config-map
      image: nginx
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config