apiVersion: v1
kind: Pod
metadata:
  name: mypod-secret
spec:
  containers:
    - name: mypod-secret
      image: redis
      volumeMounts:
        - name: foo
          mountPath: "/home/vagrant/data-volume"
          readOnly: true
  volumes:
    - name: foo
      secret:
        secretName: app-config