apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "ls /etc/config"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config

